name: Sync with Project Board

on:
  issues:
    types: [opened, edited, labeled, assigned]
  pull_request:
    types: [opened, closed, reopened, labeled]

jobs:
  sync-to-project:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Add issue or PR to project
        uses: actions/add-to-project@v0.4.0
        with:
          project-url: "https://github.com/users/alagaddonjuan/projects/1" # Correct format!
          github-token: ${{ secrets.GITHUB_TOKEN }}
