name: Project Board Sync
on:
  pull_request:
    types: [opened, closed, reopened, ready_for_review]
  issues:
    types: [opened, labeled]

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Add to project
        uses: actions/add-to-project@v0.4.0
        with:
          project-url: "https://github.com/alagaddonjuan/deptportal/projects/1"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labeled: "needs-triage"
