name: Sync with Project Board
on:
  issues:
    types: [opened, edited, labeled, assigned]
  pull_request:
    types: [opened, closed, reopened, labeled]

jobs:
  sync-to-project:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Add issues to project
        if: github.event_name == 'issues'
        uses: actions/add-to-project@v0.4.0
        with:
          project-url: "https://github.com/users/alagaddonjuan/projects/1" # Corrected URL format
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labeled: ""

      - name: Sync PR status
        if: github.event_name == 'pull_request'
        uses: srggrs/auto-sync-project@v1.0.1
        with:
          project-url: "https://github.com/users/alagaddonjuan/projects/1" # Corrected URL format
          github-token: ${{ secrets.GITHUB_TOKEN }}
          column-name: "In Review"
          done-column: "Done"
