name: Sync with Project Board
on:
  # Triggers
  issues:
    types: [opened, edited, labeled, assigned]
  pull_request:
    types: [opened, closed, reopened, labeled]

jobs:
  sync-to-project:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Add issues to project
        if: github.event_name == 'issues'
        uses: actions/add-to-project@v0.4.0
        with:
          project-url: "https://github.com/alagaddonjuan/deptportal/1" # Replace with your project URL
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labeled: ""
          
      - name: Sync PR status
        if: github.event_name == 'pull_request'
        uses: srggrs/auto-sync-project@v0.4.0
        with:
          project-url: "https://github.com/alagaddonjuan/deptportal/1"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          column-name: "In Review" # Moves PRs here when opened
          done-column: "Done" # Moves here when PR is merged

