name: Sync with Project Board

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened, closed]

jobs:
  sync-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Add to project
        uses: actions/add-to-project@v0.4.0
        with:
          project-url: "https://github.com/alagaddonjuan/deptportal/projects/1" # VERIFY THIS NUMBER
          github-token: ${{ secrets.GITHUB_TOKEN }}
